/**
 * TypeScript types for Canvas UI entities
 */

import type { UUID, NodeType, NodeAuthor, NodeStatus } from './graph';

/**
 * Canvas entity representing a named workspace
 */
export interface Canvas {
  id: UUID;
  name: string;
  description: string | null;
  graph_id: UUID;
  created_at: string; // ISO 8601 datetime
  updated_at: string; // ISO 8601 datetime
  last_opened: string; // ISO 8601 datetime
  thumbnail: string | null; // Base64-encoded image
  is_subgraph: boolean;
  owner_id: string | null;
}

/**
 * Request body for creating a canvas
 */
export interface CreateCanvasRequest {
  name: string;
  description?: string;
  owner_id?: string;
}

/**
 * Request body for updating a canvas
 */
export interface UpdateCanvasRequest {
  name?: string;
  description?: string;
}

/**
 * Response from canvas list endpoint
 */
export interface CanvasListResponse {
  canvases: Canvas[];
  total: number;
  limit: number;
  offset: number;
}

/**
 * Canvas viewport state
 */
export interface CanvasViewport {
  zoom: number; // 0.25 to 4.0 (25% to 400%)
  x: number; // X-axis pan offset
  y: number; // Y-axis pan offset
  width: number; // Viewport width in pixels
  height: number; // Viewport height in pixels
}

/**
 * Node position on canvas
 */
export interface Position {
  x: number;
  y: number;
}

/**
 * Node dimensions
 */
export interface Dimensions {
  width: number;
  height: number;
}

/**
 * Node visual styling
 */
export interface NodeStyle {
  backgroundColor: string;
  borderColor: string;
  borderWidth: number; // 1-4px based on importance
  opacity: number; // 0.5-1.0 based on importance
  shadow: string; // CSS box-shadow
}

/**
 * Visual representation of a Node on canvas
 */
export interface VisualNode {
  nodeId: UUID;
  position: Position;
  dimensions: Dimensions;
  style: NodeStyle;
  preview: string; // Truncated content (100 chars)
  // Original node data for reference
  type: NodeType;
  author: NodeAuthor;
  status: NodeStatus;
  importance: number;
}

/**
 * Edge styling
 */
export interface EdgeStyle {
  stroke: string;
  strokeWidth: number; // 1-3px
  opacity: number; // 0.6 default, 1.0 when emphasized
  animated: boolean;
}

/**
 * Connection line between nodes
 */
export interface ConnectionLine {
  id: string; // format: `${parentId}-${childId}`
  source: UUID; // Parent node ID
  target: UUID; // Child node ID
  path: string; // SVG path string (auto-generated by React Flow)
  style: EdgeStyle;
  markerEnd: string; // Arrow marker reference
}

/**
 * Rectangle for multi-selection
 */
export interface Rectangle {
  x: number;
  y: number;
  width: number;
  height: number;
}

/**
 * Interaction modes
 */
export type InteractionMode = 'select' | 'pan' | 'zoom';

/**
 * Selection state
 */
export interface SelectionState {
  selectedNodeIds: UUID[];
  hoveredNodeId: UUID | null;
  multiSelectRect: Rectangle | null;
  interactionMode: InteractionMode;
}

/**
 * UI preferences
 */
export interface UIPreferences {
  minimapVisible: boolean;
  gridVisible: boolean;
  gridSize: number; // Grid cell size in pixels
  snapToGrid: boolean;
  theme: 'light' | 'dark';
  autoFitOnLoad: boolean;
}

/**
 * Default UI preferences
 */
export const defaultPreferences: UIPreferences = {
  minimapVisible: true,
  gridVisible: true,
  gridSize: 50,
  snapToGrid: false,
  theme: 'light',
  autoFitOnLoad: true,
};
